services:
  ipsec-vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: unless-stopped 
    env_file:
      - ./ipsec-vpn/.env
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true

  wireguard:
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    environment:
      - PEERS=10
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /wireguard:/config
      - /lib/modules:/lib/modules
    
  telegram-proxy:
    image: telegrammessenger/proxy
    restart: unless-stopped
    ports:
      - 10666:443
    volumes:
      - ./telegram-proxy:/data

